import React, { ReactNode } from "react";
import Head from "next/head";
import Navbar from "../Navbar";
import { LayoutProps } from "@/type";

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className="">{children}</main>
    </>
  );
};

export default Layout;
